### ISSUE TITLE
Schema generation fails under WSL

### ISSUE THREAD

**Issue by ddhorstman** [keonik/prisma-erd-generator#65]
I'm interested in using this for a project, but I'm unable to get it to generate even a basic diagram.

UPDATE: It turns out the issue is that puppeteer, which is a dependency of mermaid, [doesn't work under WSL](https://github.com/puppeteer/puppeteer/issues/1837). There's no way you would be able to fix this.

**Comment by keonik** [comment]
Yeah, that's unfortunate. Well, there are a few ways to solve this and a few have been tossed around but not actively pursued. Maybe now is time to make issues for those.

Options
- rewrite to move away from mermaid (and puppeteer)
- Do an online version that hits an API that will generate the file for you (OS agnostic)

I was most interested in the first one but have yet to think through replacing it.

**Comment by ddhorstman** [comment]
Yeah, I think it would definitely be worth considering replacing mermaid! For what it's worth, when my colleague generated a schema for us, mermaid didn't do a very good job rendering it anyway. Although admittedly our schema is fairly complex.

![schema](https://user-images.githubusercontent.com/7649736/154758561-d9850e6a-a5ff-4dca-9653-3b4417a24519.png)

**Comment by keonik** [comment]
The [original issue](https://github.com/puppeteer/puppeteer/issues/1837) has some fixes out there for this problem related to puppeteer. Even if there isn't a fix for puppeteer, you should be able to generate a diagram in markdown because that file type skips mermaid cli and they render in markdown in github and gitlab. The other discussion is replacing mermaid with a new generator for these file types which is a larger issue. I'll open a new issue to discuss that. As of now it doesn't seem to have any traction unfortunately
